### ISSUE TITLE
Readability tweaks

### ISSUE THREAD

**Issue by r12a** [dontcallmedom/github-notify-ml#27]
> Events filtered by label "i18n", "i18n-comment", "i18n-tracking",
> "HR:i18n-comment", "HR:i18n-tracking", "i18n-review"
> Issues
> ------

It would be helpful to have a couple of lines of space above "Issues"

It would be nice to bold the repo names, so that they stand out more, but i don't know how we'd do that.  On the other hand, i made a copy with an extra line before each repo name, and it helps readability. It also helps you see the blocks related to issues closed and new comments as part of the same repo.

**Comment by r12a** [comment]
fwiw,i threw together a very quick and dirty HTML formatter for use with weekly digests to make them look prettier. Copy the issue related text from one or more digests to the small input area at https://w3c.github.io/i18n-activity/notifications/format and click outside the box.

Here's one i prepared earlier: https://w3c.github.io/i18n-activity/notifications/20170221

(i just mention it in case someone finds it useful, but not expecting that anyone will.)

**Comment by dontcallmedom** [comment]
@r12a if you feel inspired, you could turn these into HTML templates that could be sent along with the text version of the digest; if you're interested, I can give more details.

**Comment by r12a** [comment]
@dontcallmedom sure. That sounds useful.

**Comment by dontcallmedom** [comment]
@r12a so basically, the idea would be to add a `.html` version of the template(s) in [templates/generic](https://github.com/dontcallmedom/github-notify-ml/tree/master/templates/generic) - the templates are built using the [Mustache template system](https://mustache.github.io/mustache.5.html).

The simplest approach is probably to start from the existing text version and wrap it into HTML, but you'll want to use `{{` instead of `{{{` so that we get proper HTML escaping. Compared to your formatter above, I think we would want to avoid "in-your-face" URIs and instead use links on either the title or the number of the issue.

Let me know if you think this is clear enough. There will be some additional work needed on my side to make use of the new HTML templates, but having at least one of them ready (e.g. for the digests) would go a long way in motivating to do the rest of the work :)

**Comment by r12a** [comment]
Looks straightforward enough.  Is there a way for me to test the results as i'm working on it?

**Comment by dontcallmedom** [comment]
no easy way I can think of, unfortunately
