### ISSUE TITLE
email not sent due to malformed markdown link in beginning of first line ?

### ISSUE THREAD

**Issue by equalsJeffH** [dontcallmedom/github-notify-ml#35]
I submitted this issue today: w3c/webauthn#700
webauthn WG has notify-ml config'd to fwd such issue submissions to the mailing list as individual messages.  no email msg for the latter issue has appeared on the list even though I have submitted a subsequent issue w3c/webauthn#701, which has appeared on the list (and I've waited a couple hours before submitting this). 

when initially submitted, the opening parag of w3c/webauthn#700 was like so:
> CredMan](https://w3c.github.io/webappsec-credential-management/) PR w3c/webappsec-credential-management#114 "Remove the blanket restriction against nested usage" adds the `sameOriginWithAncestors parameter` to the internal methods ....

note the missing "[" (left square bracket) in front of "CredMan](..." in the first line.  

that is the only reason I can think of that this issue was not successfully forwarded to the mailing list. 

Note: i have since added the missing "[" (left square bracket) to w3c/webauthn#700

**Comment by dontcallmedom** [comment]
I had the initial event redelivered (incl the ill-formed body) and this time the [notification went through](https://lists.w3.org/Archives/Public/public-webauthn/2017Nov/0619.html).

Looking through the logs, it sounds like the server failed due to Github not sending back properly the expected IP addresses for its hooks - I'm inclined to file this as a temporary one-off error rather than a bug in the software, so I'll close this for now.
