### ISSUE TITLE
Bogus From: header when GitHub user name contains non ASCII characters

### ISSUE THREAD

**Issue by tidoust** [dontcallmedom/github-notify-ml#6]
The cedilla in my first name seems to be bogging the tool. The generated `From:` field, as seen from the mailing-list server is:

`From: =?utf-8?q?Fran=C3=A7ois_Daoust_via_GitHub_=3Csysbot+gh=40w3=2Eorg=3E?=`

The readable string generated should probably be normalized somehow. Incriminated line:
https://github.com/dontcallmedom/github-notify-ml/blob/master/index.py#L165

**Comment by dontcallmedom** [comment]
I've imported your code in the pull request I had been working on separately — thanks for looking into it, I hadn't quite found the right way yet :)

I've added tests to make sure that feature doesn't break; if you can switch back your github account to use a cedilla, we can see if that works with real servers too.

(I stupidly re-triggered the previous pull request notif, but since it read your current name and not the name at the time of the pull request, that didn't help testing)

**Comment by tidoust** [comment]
Great! I put the cedilla back on my GitHub profile.
